name: flutter_scroll_app
description: "https://github.com/nikitaessen/flutter-scroll-app/blob/master/README.md"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.5
  dio: ^5.4.3+1
  equatable: ^2.0.5
  bloc: ^8.1.4
  get_it: ^7.7.0
  injectable: ^2.4.1
  json_annotation: ^4.9.0
  auto_route: ^8.1.3
  mocktail: ^1.0.3
  transparent_image: ^2.0.1
  golden_toolkit: ^0.15.0
  network_image_mock: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  injectable_generator: ^2.4.1

  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0

  json_serializable: ^6.8.0
  auto_route_generator: ^8.0.0
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: ArchivoBlack
      fonts:
        - asset: assets/fonts/ArchivoBlack-Regular.ttf

flutter_gen:
  output: lib/src/assets/
  line_length: 100
  assets:
    enabled: true
    outputs:
      class_name: ScrollAppAssets

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
